// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBTeach.Data.Models;

namespace UBTechApi.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20200804105936_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UBTeach.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            FirstName = "John",
                            LastName = "Doe",
                            Role = "CTO"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            FirstName = "Mosh",
                            LastName = "Zeev",
                            Role = "Dev"
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            FirstName = "Guy",
                            LastName = "Tzof",
                            Role = "QA"
                        },
                        new
                        {
                            Id = 4,
                            Age = 24,
                            FirstName = "Noam",
                            LastName = "Cohen",
                            Role = "Dev"
                        },
                        new
                        {
                            Id = 5,
                            Age = 30,
                            FirstName = "Avi",
                            LastName = "Avraham",
                            Role = "PO"
                        },
                        new
                        {
                            Id = 6,
                            Age = 22,
                            FirstName = "Yochai",
                            LastName = "Moalem",
                            Role = "Dev"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
